import React from 'react';
// import Button from '@material-ui/core/Button';
import veganEats from './images/VeganEats.png';
// import veganMap from './images/veganEatsMap.png';
// import veganContact from './images/veganContact.png';
import triviaHome from './images/triviaHome.png';
// import triviaQ from './images/triviaQ.png';
// import triviaAbout from './images/triviaAbout.png';
import gardenHome from './images/gardenHome.png';
// import gardenPlay from './images/gardenPlay.png';
// import gardenSeed from './images/gardenSeed.png';
// import gardenPlant from './images/gardenPlant.png';
// import gardenGreen from './images/gardenGreenhouse.png'
// import { Card} from 'react-materialize';
// import computer from './images/computer.jpg';
import blur from './images/project.jpg';



import './projects.css';

function Projects (){
    return(
      <div className="projects">
      <h2 className="responsive-img projectTitle"><i class="responsive-img fas fa-edit"></i>Projects</h2>
      {/* <img className="responsive-img blur" src={blur} alt="projectpic"/> */}
  <div class="col s12 m7">
    <h3 class="header">Vegan:Eats!</h3>
    <div class="card horizontal">
      <div class="card-image  hide-on-small-only">
        <img class="responsive-img" src={veganEats} alt="veganeats"></img>
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <p>Created a website for vegetarians and vegans to dine out at local restarurants and grocery stores in downtown Salt Lake City, UT.</p>
          <p>Used React to create the front-end, responsive, and Google Maps is integrated to the application. </p>
        </div>
        <div class="card-action">
          <a href="http://veganeats.surge.sh/">Vegan:Eats! website</a>
        </div>
      </div>
    </div>
  </div>
          
  <div class="col s12 m7">
    <h3 class="header">Trivia Game</h3>
    <div class="card horizontal">
      <div class="card-image hide-on-small-only">
        <img class="responsive-img" src={triviaHome} alt="trivia"></img>
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <p>A CRUD single-page application built with React.</p>
          <p>Each trivia question is generated by using content delivered by the API.</p>
        </div>
        <div class="card-action">
          <a href="http://triviagame.surge.sh/">Trivia Game website</a>
        </div>
      </div>
    </div>
  </div>
       <div class="col s12 m7">
    <h3 class="header">Garden Game</h3>
    <div class="card horizontal">
      <div class="card-image hide-on-small-only">
        <img class="responsive-img" src={gardenHome} alt="gardenHome"></img>
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <p>A CRUD single-page application built with React on the front-end.</p>
          <p>Used Node.js/Express as the back-end server and Mongoose and MongoDB for the database.</p>
          <p>A Learning game about gardening for children.</p>
        </div>
        <div class="card-action">
          <a href="https://gardengame.herokuapp.com/">Garden Party website</a>
        </div>
      </div>
    </div>
  </div>
  </div>
  
   )
}
export default Projects;