import React from 'react';
import veganEats from './images/VeganEats.png';
import triviaHome from './images/triviaHome.png';
import gardenHome from './images/gardenHome.png';
import './projects.css';

function Projects (){

    return(
      <div className="projects">
      <h2 className="projectTitle hide-on-small-only"><i class="responsive-img fas fa-edit"></i>Projects</h2>   
  <div class="col s12 m7">
    {/* <h3 class="header">Vegan:Eats!</h3> */}
    <div class="card horizontal">
      <div class="card-image  hide-on-small-only">
        <img class="responsive-img" src={veganEats} alt="veganeats"></img>
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <h3>Vegan:Eats!</h3>
          <p>Created a website for vegetarians and vegans to dine out at local restaurants and grocery stores in downtown Salt Lake City, UT.</p>
          <p>Used React to create the front-end, responsive, and Google Maps is integrated to the application. </p>
        </div>
        <div class="card-action">
          <a href="http://veganeats.surge.sh/" target="_blank" rel="noopener noreferrer">Website</a>
          <a href="https://github.com/veronicagiraldo/Vegan-Eats" target="_blank" rel="noopener noreferrer">View code on github</a>
        </div>
      </div>
    </div>
  </div>
          
  <div class="col s12 m7">
    {/* <h3 class="header">Trivia Game</h3> */}
    <div class="card horizontal">
      <div class="card-image hide-on-small-only">
        <img class="responsive-img" src={triviaHome} alt="trivia"></img>
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <h3>Trivia Game</h3>
          <p>A CRUD single-page application built with React.</p>
          <p>Each trivia question is generated by using content delivered by the API.</p>
        </div>
        <div class="card-action">
          <a href="http://triviagame.surge.sh/" target="_blank" rel="noopener noreferrer">Website</a>
          <a href="https://github.com/veronicagiraldo/Trivia-Game" target="_blank" rel="noopener noreferrer">View code on github</a>
        </div>
      </div>
    </div>
  </div>
       <div class="col s12 m7">
    {/* <h3 class="header">Garden Game</h3> */}
    <div class="card horizontal">
      <div class="card-image hide-on-small-only">
        <img class="responsive-img" src={gardenHome} alt="gardenHome"></img>
      </div>
      <div class="card-stacked">
        <div class="card-content">
              <h3>Garden Game</h3>
          <p>A CRUD single-page application built with React on the front-end.</p>
          <p>Used Node.js/Express as the back-end server and Mongoose and MongoDB for the database.</p>
          <p>A Learning game about gardening for children.</p>
        </div>
        <div class="card-action">
          <a href="https://gardengame.herokuapp.com/" target="_blank" rel="noopener noreferrer">Website</a>
          <a href="https://github.com/veronicagiraldo/Garden-Game" target="_blank" rel="noopener noreferrer">View code on github</a>
        </div>
      </div>
    </div>
  </div>
  </div>
   
 

   )
}
export default Projects;